openapi: 3.0.3
info:
  title: Common definitions for Candor Api
  version: 0.17.0
  contact:
    name: Candor Api Specification
    url: https://github.com/candorfintech/Candor.Api.OpenAPI
externalDocs:
  description: Changelog
  url: https://github.com/candorfintech/Candor.Api.OpenAPI#changelog
servers:
  - description: Development
    url: 'https://api-dev.candortechnology.com'
  - description: Staging
    url: 'https://api-stage.candortechnology.com'
  - description: Production
    url: 'https://api.candortechnology.com'

paths:
  /:
    description: See a definition specific specification
components:
  parameters:
    LoanId:
      name: id
      description: The unique identifier for this loan application.
      in: path
      required: true
      example: c8e27489-0381-438f-8148-4b7a2379a64c
      schema:
        $ref: '#/components/schemas/LoanId'

  schemas:
    LoanId:
      type: string
      title: LoanId
      description: The unique identifier for this loan application.
      minLength: 1

    LoanName:
      type: string
      title: LoanName
      description: The client name for this loan
      minLength: 1

    Context:
      type: string
      title: Context
      description: A value used by the caller to track the state around this request. If one is supplied, it must be returned as specified.

    LoanDataType:
      type: string
      title: Loan Data Type
      description: |
        The various loan data types that can be associated with the loan.
        - URLA: Universal Residential Loan Application
        - DUXML: Fannie Mae Desktop Underwriter
        - LPAXML: Loan Product Advisor
        - CREDIT: Credit Provider's Xml (Core Logic)
        - FLOODCERT: Flood Certification (Core Logic)
        - TWNXML: Work Number
        - FINICITY: Verification of assets vendor
        - FRMFREE: Asset Validation
      enum:
      - URLA
      - DUXML
      - LPAXML
      - CREDIT
      - FLOODCERT
      - TWNXML
      - FINICITY
      - FRMFREE

    StatusType:
      type: string
      enum:
      - Pending
      - Valid
      - Invalid

    UploadDocumentRequest:
      type: object
      title: Upload Document Request
      required:
      - documents
      properties:
        documents:
          type: array
          description: A collection of documents requesting to be uploaded.
          items:
            type: object
            description: Metadata about the document requesting to be uploaded.
              Either the `id`, `filename`, or both must be provided.
            minItems: 1
            properties:
              id:
                type: string
                description: |
                  A unique identifier for this document in the context of this loan. If one is not supplied, one will be created by the Candor Api. It is recommended to stick with the following characters:

                  - `0`-`9`
                  - `a`-`z`
                  - `A`-`Z`
                  - Exclamation point: `!`
                  - Hyphen: `-`
                  - Underscore: `_`
                  - Period: `.`
                  - Asterisk: `*`
                  - Single quote: `'`
                  - Open parentheses: `(`
                  - Close parentheses: `)`
              filename:
                type: string
                description: The filename, e.g., "April Bank Statement.pdf"

    UploadDocumentResponse:
      type: object
      title: Upload Document Response
      required:
      - id
      - documents
      properties:
        id:
          $ref: '#/components/schemas/LoanId'
        documents:
          type: array
          description: A collection of successful or failed document upload requests.
          items:
            type: object
            description: Results of a document upload request. It'll either contain the `upload` location, or an `error`.
            required:
            - id
            properties:
              id:
                type: string
                description: The original `id` supplied in the request if present, or a unique identifier created for this document by the Candor Api.
              error:
                type: string
                description: If an error occurred while trying to complete the upload request for this document, this will contain the error message.
              upload:
                type: object
                required:
                - url
                properties:
                  url:
                    type: string
                    format: uri
                    description: If this document request is valid, this will contain the Url where the document can be uploaded using the `PUT` verb. NOTE, there is an expiration time to this upload url. So it is best to make this request right when you are ready to upload the document.
                  headers:
                    type: object
                    description: Required custom headers that need to be used during the upload PUT request.
                    additionalProperties:
                      type: string

    ProcessLoanBase:
      type: object
      properties:
        responseType:
          type: string
          description: |
            This drives the response type back to the LOS. The system default is `Asynchronous` which can be overridden as a Customer setting, and then additionally overridden here per request.

            - `Asynchronous`: A `202` response will be returned and the body will **not** contain a Candor Result.
            - `Synchronous`: A `200` response will be returned with a Candor Result in the body.

            If `documentsToProcess` are present, the Candor Results of the processed documents will always be an Asynchronous callback notification. If the original request was also `Asynchronous`, then there will only be one Candor Results returned after documents are processed as a callback notification. If the original request was `Synchronous`, then a loan data Candor Result will be returned in the response followed by another Candor Result for the processed documents which be sent as a callback notification.
          default: Asynchronous
          enum:
          - Asynchronous
          - Synchronous
        context:
          $ref: '#/components/schemas/Context'
        emails:
          type: array
          title: Emails
          description: |
            Deprecated: see `loanEmails`.

            A list of emails to notify when a Candor Result is processed.
          deprecated: true
          items:
            type: object
            required:
            - email
            - type
            properties:
              email:
                type: string
              type:
                type: string
                enum:
                - Processor
                - Underwriter
                - LoanOfficer
        loanEmails:
          type: array
          title: Notification Emails
          description: |
            **Supersedes `emails` property**

            A list of email addresses that will receive an email notification message when results have been processed.
          items:
            type: string
        investors:
          type: array
          title: Investors
          description: A list of investors for this loan
          minItems: 1
          items:
            type: object
            required:
              - name
              - productName
            properties:
              name:
                type: string
              productName:
                type: string
        gse:
          type: string
          enum:
          - FannieMae
          - FreddieMac

    CandorResult:
      type: object
      title: Candor Result
      properties:
        loanId:
          $ref: '#/components/schemas/LoanId'
        loanName:
          $ref: '#/components/schemas/LoanName'
        runId:
          type: integer
          description: The number of times that findings have been processed on this loan document
        timestamp:
          type: string
          format: date-time
          description: An ISO-8601 formatted date/time of when this was result was generated
        context:
          $ref: '#/components/schemas/Context'
        insuranceScore:
          type: string
          description: Candor Score up to 100 that identifies how hard or easy a loan is to close based on outstanding conditions and their difficulty to obtain. The higher the score the easier to close.
        insuranceCovered:
          type: string
          enum:
          - Pending
          - Available
          - Unavailable
        underwritingStatus:
          type: string
          description: Overall underwriting status on the loan document. Note that `Candor Cleared` means that all "Candor" related conditions have been cleared on a loan document. There may be "Lender" related conditions for items such as a Credit Inquiry Letter, Title, Mortgage Statement still needed; however, Candor has completed it's analysis of the document.
          enum:
          - Conditional Approval
          - Suspended
          - Declined
          - Candor Cleared
        occupancy:
          type: number
          description: Candor analytic related to Occupancy.
          nullable: true
        identity:
          type: number
          description: Candor analytic related to Borrower Identity, SSN, etc.
          nullable: true
        valuation:
          type: number
          description: Candor analytic related to Property Value, Appraisal, etc.
          nullable: true
        liabilities:
          type: number
          description: Candor analytic related to Liabilities and Credit items.
          nullable: true
        assets:
          type: number
          description: Candor analytic related to Assets, Bank Statements, Large Deposits, etc.
          nullable: true
        income:
          type: number
          description: Candor analytic related to Income, Employment, Paystubs, W2s, etc.
          nullable: true
        conditions:
          type: array
          title: Conditions
          items:
            title: Condition
            properties:
              lesId:
                type: string
                description: Unique identifier for the condition that is
                  maintained between all runs.
              conditionId:
                type: string
                description: |
                  Identifier for the condition for this run. Note: The same
                  condition could be created with different `conditionId` values
                  between runs. Use `lesId` for a consistent unique identifier
                  between runs.
              status:
                type: string
                # LoanDepot: Unfulfilled -> 0, Fulfilled -> 1
                enum:
                  - Unfulfilled
                  - Fulfilled
              name:
                type: string
                description: Condition assigned name for condition
              description:
                type: string
                description: Candor provided actual condition verbiage that clearly defines requirements to clear the condition
              priorTo:
                type: string
                description: |
                  - PTA: Prior to Approval, Suspended, Declined
                  - PTD: Prior to Documents
                  - AC: Prior to Closing
                  - PTF: Prior to Funding
                  - Notifications
                # LoanDepot: AC -> PTC
                enum:
                - PTA
                - PTD
                - AC
                - PTF
                - Notifications
              owner:
                type: string
                description: This identifies the responsible party for the condition
                enum:
                - Candor
                - Lender
              category:
                type: string
                description: |
                  - Credit - Identity
                  - Credit - Occupancy
                  - Credit
                  - Income (i.e., Income/Employment)
                  - Assets
                  - Property
                  - Legal (i.e., Legal/Compliance)
                enum:
                - Credit - Identity
                - Credit - Occupancy
                - Credit
                - Income
                - Assets
                - Property
                - Legal
        results:
          type: array
          title: Results
          items:
            title: Candor Result
            properties:
              name:
                type: string
                description: The name of the result document.
              section:
                type: string
                description: A section/folder container for this document.
              base64:
                type: string
                description: The result document binary Base64 encoded.
        documentsProcessed:
          type: array
          title: Documents Processed
          items:
            type: object
            title: Processed Document
            required:
            - fileId
            - parentFileId
            - status
            properties:
              fileId:
                type: string
                description: The Candor Api unique identifier for this document
              parentFileId:
                type: string
                description: The unique identifier of the source document (original inputDocument).
              status:
                type: object
                properties:
                  code:
                    type: integer
                    description: |
                      The processed status for this document

                      - 200: Successfully ICR'd
                      - 300: Duplicate Document Uploaded
                      - 301: Illegible Document
                      - 302: Ineligible Document
                      - 350: Partially ICR'd
                      - 400: Document Corrupted, Unable to open, or Editable pdf
                      - 401: Unable to match Borrower name on document to applicant; Lender to review
                      - 402: Unable to match SSN on document to applicant; Lender to review
                      - 403: Unable to match Employer on document to application; Lender to review
                      - 404: Unable to match Company Name on document to application; Lender to review
                      - 405: Document is outdated per guideline requirements
                      - 406: Successfully ICR'd
                      - 500: Failed ICR'd
                    # Input Document Status Result
                    # 406 -> 200
                    enum:
                    - 200
                    - 300
                    - 301
                    - 302
                    - 350
                    - 400
                    - 401
                    - 402
                    - 403
                    - 404
                    - 405
                    - 406
                    - 500
                  message:
                    type: string
        liv:
          type: object
          title: LIV (Loan Income Verification)
          description: |
            Soon to be released
            Breaks down the sources of income that Candor identified.
          properties:
            income:
              type: array
              items:
                properties:
                  documentType:
                    type: string
                  documentData:
                    type: array
                    description: A dynamic array of values found in the document. The document type greately affects the values that can be found.
                    items:
                      properties:
                        key:
                          type: string
                        value:
                          type: string
